// Link-preview image with the exact match %: GET /<hobby-slug>/<percent>.png
// Lays the pre-drawn badge for that % (website/previews/badges/<n>.png) over the hobby's
// card (website/previews/<slug>.jpg), both generated by `swift run ExportCatalog website`,
// so the image keeps the Apple emoji and fonts. Responses are cached at Vercel's edge for a year.
import { ImageResponse } from "@vercel/og";
import slugs from "../slugs.json" with { type: "json" };

export const config = { runtime: "edge" };

const ASSETS = globalThis.process?.env?.PREVIEW_ASSETS || "https://amalmehta.github.io/HobbyMaxer/previews/";
// Same spot as Previews.badgeOrigin in Sources/ExportCatalog/Previews.swift.
const BADGE = { left: 235, top: 344, size: 168 };

export default function handler(request) {
  const params = new URL(request.url).searchParams;
  const slug = params.get("h");
  const percent = /^(100|[1-9]?\d)\.png$/.exec(params.get("f") ?? "")?.[1];
  if (!slugs.includes(slug) || percent === undefined) return new Response("Not found", { status: 404 });

  const img = (src, style) => ({ type: "img", props: { src, width: style.width, height: style.height, style: { position: "absolute", ...style } } });
  return new ImageResponse(
    {
      type: "div",
      props: {
        style: { display: "flex", width: "100%", height: "100%", position: "relative" },
        children: [
          img(`${ASSETS}${slug}.jpg`, { left: 0, top: 0, width: 1200, height: 630 }),
          img(`${ASSETS}badges/${percent}.png`, { left: BADGE.left, top: BADGE.top, width: BADGE.size, height: BADGE.size }),
        ],
      },
    },
    { width: 1200, height: 630, headers: { "Cache-Control": "public, max-age=31536000, immutable" } },
  );
}
